'use client';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useState} from 'react';
import {AlertTriangle,Coins,Users,Wind,MapPin,Navigation,Search,Sun,Download,SlidersHorizontal,ArrowUpRight,Leaf} from 'lucide-react';
import {useBundle,useScenarios,assetStatus,inr,number,downloadJson} from '@/lib/data';
import {useApp} from '@/lib/store';
import {PageHeading,Panel,Stat,Status,Provenance,Loading,ErrorState} from '@/components/ui';
import {Replay} from '@/components/replay';
const FarmScene=dynamic(()=>import('@/components/farm-scene'),{ssr:false,loading:()=> <div className="scene-loading"><Wind size={32}/><span>Preparing the site twin…</span></div>});
export default function FleetPage(){const b=useBundle(),s=useScenarios();const router=useRouter();const state=useApp();const [filter,setFilter]=useState('all');const [query,setQuery]=useState('');
 if(b.isPending||s.isPending)return <Loading/>;if(!b.data||!s.data)return <ErrorState message="The demo artifacts are unavailable." retry={()=>{b.refetch();s.refetch();}}/>;
 const bundle=b.data;const scenario=s.data[0];const signal=scenario.data[state.step];const alertIndex=scenario.alarms[state.model];
 const select=(id:string)=>{state.selectAsset(id);router.push(id.startsWith('S')?'/solar/':'/investigate/');};
 const alerts=bundle.alerts.filter(a=>a.asset_id!=='T-03'||state.step>=(alertIndex??Infinity));
 const assets=bundle.assets.filter(a=>(filter==='all'||a.type===filter)&&(a.id+' '+a.name).toLowerCase().includes(query.toLowerCase()));
 return <><PageHeading title="A clearer view. A healthier fleet." description="See the signal. Make the right call." actions={<div className="site-select"><span>Site</span><div><MapPin size={16}/><strong>{bundle.site.name}</strong><small>Gujarat</small></div></div>}/>
 <div className="stats-strip"><Stat label="Assets at risk" value={String(alerts.length)} detail={`of ${bundle.assets.length} demonstration assets`} icon={<AlertTriangle size={23}/>}/><Stat label="Estimated exposure" value={inr(alerts.reduce((t,a)=>t+(bundle.assets.find(x=>x.id===a.asset_id)?.exposure_inr||0),0))} detail="Illustrative cost of inaction" icon={<Coins size={24}/>}/><Stat label="Available crews" value={String(state.crewCount)} detail="Edit capacity in Maintenance" icon={<Users size={24}/>}/><div className="strip-caption"><Sun size={24}/><span>Renewable today.<br/>Resilient tomorrow.</span></div></div>
 <div className="fleet-grid"><section className="twin-panel"><div className="scene-area"><div className="scene-title"><Wind size={28}/><div><h2>Site twin</h2><span>Schematic layout · drag to explore</span></div></div><div className="scene-provenance"><Provenance/></div><FarmScene assets={bundle.assets} onSelect={select} warning={state.step>=(alertIndex??Infinity)}/><div className="scene-weather"><Wind size={15}/><b>{signal.wind_speed} m/s</b><span>·</span><Sun size={15}/><b>{signal.ambient_temperature}°C</b><small>Simulated</small></div><div className="compass"><span>N</span><Navigation size={26}/></div></div><Replay scenario={scenario}/></section>
 <Panel title="Needs attention" action={<span className="count-pill">{alerts.length}</span>} className="attention-panel"><div className="attention-list">{alerts.map(a=><article key={a.id} className="attention-item"><div className={`attention-icon ${a.severity==='Warning'?'orange':'amber'}`}>{a.asset_id.startsWith('S')?<Sun size={19}/>:<AlertTriangle size={19}/>}</div><div className="attention-body"><div className="row-between"><strong>{a.asset_id}</strong><button className="icon-button" aria-label={`Open ${a.asset_id}`} onClick={()=>select(a.asset_id)}><ArrowUpRight size={16}/></button></div><p>{a.title}</p><div className="row-between"><Status value={state.acknowledged.includes(a.id)?'Acknowledged':a.severity}/><button className="button secondary small" onClick={()=>select(a.asset_id)}><Search size={12}/>Investigate</button></div></div></article>)}</div><div className="attention-note"><Leaf size={24}/><div><strong>Keep your fleet performing</strong><p>Investigate signals, plan maintenance and align crews to reduce risk.</p></div></div></Panel></div>
 <Panel title="Asset health" subtitle="One place to see every asset and its next action." action={<div className="table-tools"><div className="segmented" aria-label="Asset type filter">{[['all','All assets'],['wind','Wind'],['solar','Solar']].map(([value,label])=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{label}</button>)}</div><button className="icon-button" aria-label="Export asset data" onClick={()=>downloadJson('urjakavach-assets.json',{provenance:'Simulated',assets})}><Download size={17}/></button></div>}>
 <div className="table-search"><Search size={15}/><input aria-label="Search fleet assets" placeholder="Search asset ID or name" value={query} onChange={e=>setQuery(e.target.value)}/><SlidersHorizontal size={15}/><span>{assets.length} assets</span></div><div className="table-scroll"><table><thead><tr><th>Asset</th><th>Type</th><th>Status</th><th>Output</th><th>Risk index</th><th>Next action</th></tr></thead><tbody>{assets.map(a=><tr key={a.id}><td><button className="asset-id" onClick={()=>select(a.id)}>{a.type==='wind'?<Wind size={16}/>:<Sun size={16}/>}<strong>{a.id}</strong></button></td><td>{a.type==='wind'?'Wind turbine':'Solar block'}<small className="cell-sub">{number(a.capacity_kw)} kW rated · assumed</small></td><td><Status value={assetStatus(a.id,state.step,alertIndex,a.status)}/></td><td className="numeric">{number(a.id==='T-03'?signal.power:a.power_kw)} <span className="muted">kW</span></td><td><div className="risk-inline"><span style={{width:50}}><i style={{width:`${a.risk}%`,background:a.risk>=80?'#ce703b':'#73977f'}}/></span>{a.risk}<small>/100</small></div></td><td><button className="button ghost small" onClick={()=>select(a.id)}>View asset<ArrowUpRight size={13}/></button></td></tr>)}</tbody></table>{assets.length===0&&<div className="empty-state">No matching assets. Try a different search.</div>}</div></Panel><div className="page-footnote"><Provenance/><span>Risk indices and telemetry are illustrative. <Link href="/performance/">See evidence status</Link>.</span></div></>;
}
