'use client';
import Link from 'next/link';
import {useState} from 'react';
import {CalendarDays,Plus,Minus,LockKeyhole,Download,Check,Clock,Users,LoaderCircle,ClipboardPlus,ArrowRightLeft,Wind,CloudRain} from 'lucide-react';
import {usePlans,useApiStatus,api,inr,downloadJson} from '@/lib/data';
import {useApp} from '@/lib/store';
import type {Schedule,ScheduleItem,WorkOrder} from '@/lib/types';
import {PageHeading,Panel,Stat,Status,Notice,Loading,ErrorState} from '@/components/ui';
import {LossExplorer} from '@/components/loss-explorer';
function describeDiff(before:Schedule|undefined,after:Schedule){if(!before)return after.changes;const differences:string[]=[];for(const item of after.items){const old=before.items.find(o=>o.job_id===item.job_id);if(!old)differences.push(`${item.asset_id} is now assigned to Crew ${item.crew+1}.`);else if(item.start_hour!==old.start_hour||item.crew!==old.crew)differences.push(`${item.asset_id}: Crew ${old.crew+1}, day ${Math.floor(old.start_hour/24)+1} → Crew ${item.crew+1}, day ${Math.floor(item.start_hour/24)+1}.`);}for(const old of before.items)if(!after.items.some(i=>i.job_id===old.job_id))differences.push(`${old.asset_id} is now unscheduled. Review the reason below.`);return differences.length?differences:['The existing assignments remain feasible; no job moved.'];}
export default function MaintenancePage(){const q=usePlans(),status=useApiStatus();const state=useApp();const [active,setActive]=useState('2|7|balanced|0|0');const [livePlan,setLivePlan]=useState<Schedule|null>(null);const [diff,setDiff]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<ScheduleItem|null>(null);
 if(q.isPending)return <Loading/>;if(!q.data)return <ErrorState message="The precomputed plan catalog is unavailable." retry={()=>q.refetch()}/>;
 const key=`${state.crewCount}|${state.horizon}|${state.profile}|${state.jobDelay}|${Number(state.locked)}`;const plan=livePlan||q.data[active];const dirty=key!==active;
 const optimize=async()=>{setBusy(true);try{const next=status.data?await api<Schedule>('/schedule/optimize','POST',{crew_count:state.crewCount,horizon_days:state.horizon,profile:state.profile,delay_days:state.jobDelay,locked:state.locked,previous:plan.items}):q.data![key];if(!next)throw new Error('This custom scenario requires the Python API.');setDiff(describeDiff(plan,next));setLivePlan(status.data?next:null);setActive(key);setSelected(null);state.notify(status.data?'Schedule optimized.':'Precomputed CP-SAT plan loaded.');}catch(e){state.notify(e instanceof Error?e.message:'Could not optimize the schedule.');}finally{setBusy(false);}};
 const createOrders=async()=>{let added=0;for(const item of plan.items){if(state.orders.some(o=>o.asset_id===item.asset_id&&o.status!=='Completed'))continue;const order:WorkOrder={id:`WO-${item.job_id}`,asset_id:item.asset_id,title:item.title,status:'Assigned',priority:item.risk>=70?'High':'Medium',crew:`Crew ${item.crew+1}`,skill:item.skill,duration_hours:item.duration_hours,provenance:'Simulated',notes:`Planned for day ${Math.floor(item.start_hour/24)+1} at ${item.start_hour%24}:00.`,checklist:[{text:'Confirm work authorization and site-approved safety procedure',done:false},{text:'Review the alert evidence and inspect the asset',done:false},{text:'Record findings, photos and parts used',done:false},{text:'Request supervisor review before return to service',done:false}]};if(status.data)try{await api('/workorders','POST',order);}catch{state.notify('Some orders are saved locally; API sync failed.');}state.addOrder(order);added++;}state.notify(added?`${added} work orders created. Open the technician app to begin.`:'These assets already have open work orders.');};
 return <><PageHeading title="The right repair. At the right time." description="Balance risk, crew capacity and safe access windows." actions={<><button className="button secondary" onClick={()=>downloadJson('urjakavach-maintenance-plan.json',plan)}><Download size={14}/>Export plan</button><button className="button primary" disabled={dirty||!plan.items.length} onClick={createOrders}><ClipboardPlus size={14}/>Create work orders</button></>}/>
 <div className="planner-top"><Panel><div className="planner-controls"><div><label className="form-label">Available crews</label><div className="stepper"><button aria-label="Remove one crew" disabled={state.crewCount===1} onClick={()=>state.setPlanner({crewCount:state.crewCount-1})}><Minus size={14}/></button><output aria-label="Available crew count">{state.crewCount}</output><button aria-label="Add one crew" disabled={state.crewCount===4} onClick={()=>state.setPlanner({crewCount:state.crewCount+1})}><Plus size={14}/></button></div></div><div><label className="form-label" htmlFor="horizon">Planning horizon</label><select id="horizon" value={state.horizon} onChange={e=>state.setPlanner({horizon:+e.target.value})}><option value={3}>3 days</option><option value={5}>5 days</option><option value={7}>7 days</option></select></div><div><label className="form-label" htmlFor="profile">Crew skills</label><select id="profile" value={state.profile} onChange={e=>state.setPlanner({profile:e.target.value})}><option value="balanced">Balanced team</option><option value="mechanical">Mechanical only</option><option value="electrical">Electrical only</option><option value="solar">Solar only</option></select></div><button className="button primary" onClick={optimize} disabled={busy}>{busy?<LoaderCircle size={14} className="spin"/>:<CalendarDays size={14}/>}Optimize schedule</button></div>{dirty&&<div className="pending-controls">Controls changed. Optimize to apply the new scenario.</div>}</Panel><Panel><div className="metrics-row"><Stat label="Estimated loss avoided" value={inr(plan.loss_avoided_inr)}/><Stat label="Risk covered" value={`${plan.risk_covered_pct}%`}/><Stat label="Crew utilization" value={`${plan.crew_utilization_pct}%`}/></div></Panel></div>
 <div className="planner-grid section-gap"><div className="stack"><Panel title="Crew schedule" subtitle={`Scenario-relative working days · ${plan.crew_count} crews · ${plan.horizon_days} days`} action={<span className="chip">{plan.optimal?'Optimal solution':'Feasible solution'}</span>}><div className="gantt-scroll"><div className="gantt" style={{minWidth:Math.max(520,plan.horizon_days*95)}}><div className="gantt-head"><div>Assignment</div>{Array.from({length:plan.horizon_days},(_,i)=><div key={i}>Day {i+1}<small>08:00–17:00</small></div>)}</div>{Array.from({length:plan.crew_count},(_,c)=><div className="gantt-row" key={c}><div className="gantt-crew"><Users size={15}/><strong>Crew {c+1}</strong></div><div className="gantt-track"><div className="gantt-grid">{Array.from({length:plan.horizon_days},(_,d)=><div key={d} className={d===1?'weather-block':''}/>)}</div>{plan.items.filter(i=>i.crew===c).map(item=>{const packed=Math.floor(item.start_hour/24)*9+item.start_hour%24-8;return <button key={item.job_id} className={`gantt-job ${item.skill==='solar'?'solar':item.skill==='electrical'?'electrical':''} ${selected?.job_id===item.job_id?'selected':''}`} style={{left:`${packed/(plan.horizon_days*9)*100}%`,width:`${item.duration_hours/(plan.horizon_days*9)*100}%`}} title={`${item.asset_id} · ${item.title} · ${item.start_hour%24}:00–${item.end_hour%24}:00, day ${Math.floor(item.start_hour/24)+1}`} onClick={()=>setSelected(item)}>{item.locked&&<LockKeyhole size={10}/>}<strong>{item.asset_id}</strong><small>{item.duration_hours}h</small></button>;})}</div></div>)}</div></div><div className="gantt-legend"><span><i className="legend-dot"/>Mechanical</span><span><i className="legend-dot blue"/>Electrical</span><span><i className="legend-dot orange"/>Solar</span><span><Clock size={11}/>1-hour transfer between groups</span></div>{selected&&<div className="selected-job"><div><strong>{selected.asset_id} · {selected.title}</strong><p>Crew {selected.crew+1} · Day {Math.floor(selected.start_hour/24)+1}, {selected.start_hour%24}:00–{selected.end_hour%24}:00 · Estimated loss {inr(selected.expected_loss_inr)}</p></div><Link className="button secondary small" href="/tech/">Open work orders</Link></div>}<div className="weather-note"><Wind size={13}/><span>Day 2: wind work starts after 12:00.</span><CloudRain size={13}/><span>Day 3: no module cleaning.</span><small>Simulated access windows</small></div></Panel>
 <Panel title="Candidate jobs" subtitle="Skills, shifts, access, parts and inter-group travel are hard constraints."><div className="table-scroll"><table><thead><tr><th>Asset</th><th>Task</th><th>Risk index</th><th>Duration</th><th>Parts ready</th><th>Lock</th></tr></thead><tbody>{plan.jobs.map(j=><tr key={j.id}><td><strong>{j.asset_id}</strong></td><td>{j.title}<small className="cell-sub">{j.skill}</small></td><td><Status value={j.risk>=70?'High':j.risk>=40?'Medium':'Low'}/></td><td>{j.duration_hours}h</td><td>{j.parts_ready_hour===0?'Now':`Day ${Math.floor(j.parts_ready_hour/24)+1}`}</td><td>{j.id==='J-101'?<input type="checkbox" aria-label="Lock T-03 at day 1, 10 AM with Crew 1" checked={state.locked} onChange={e=>state.setPlanner({locked:e.target.checked})}/>:<span className="muted" title="Custom locks can be submitted to the Python API">—</span>}</td></tr>)}</tbody></table></div><div className="job-delay"><label htmlFor="job-delay">Delay T-03 by <strong>{state.jobDelay} days</strong></label><input id="job-delay" type="range" min={0} max={3} value={state.jobDelay} onChange={e=>state.setPlanner({jobDelay:+e.target.value})}/><small>A lock remains fixed; a conflicting delay produces an unscheduled reason.</small></div></Panel>
 {plan.unscheduled.length>0&&<Panel title={`Unscheduled jobs · ${plan.unscheduled.length}`}><div className="panel-body">{plan.unscheduled.map(j=><div className="unscheduled-row" key={j.job_id}><strong>{j.asset_id}</strong><div>{j.title}<p>{j.reason}</p></div></div>)}</div></Panel>}
 </div><div className="stack"><Panel title="What changed" action={<ArrowRightLeft size={16}/>}><div className="change-list">{(diff.length?diff:plan.changes.slice(0,3)).map((d,i)=><div key={i}><span/><p>{d}</p></div>)}</div><div className="solver-note"><Check size={13}/><span>{status.data?'Live Python solve':'Precomputed Python CP-SAT plan'}<small>Recorded solve: {plan.elapsed_ms.toFixed(1)} ms · {plan.solver_status}</small></span></div></Panel><Panel title="Cost of waiting" subtitle="A separate T-03 exposure scenario."><div className="panel-body"><LossExplorer compact/></div></Panel></div></div>
 <Panel title="Schedule comparison" subtitle="Every policy uses the same simulated jobs, hard constraints and cost assumptions." className="section-gap"><div className="baseline-grid">{[{name:'CP-SAT optimized',value:plan,active:true},{name:'Highest risk first',value:plan.baselines.risk_first,active:false},{name:'Calendar order',value:plan.baselines.calendar,active:false}].map(x=><div className={`baseline-card ${x.active?'chosen':''}`} key={x.name}><h3>{x.active&&<Check size={15}/>} {x.name}</h3><div><span>Estimated loss</span><strong>{inr(x.value.expected_loss_inr)}</strong></div><div><span>Risk covered</span><strong>{x.value.risk_covered_pct}%</strong></div><div><span>Unscheduled jobs</span><strong>{x.value.unscheduled.length}</strong></div></div>)}</div></Panel><div className="section-gap"><Notice>Planner costs and access windows are illustrative. The separate loss explorer uses editable uncertainty assumptions; it is not a calibrated production failure model. <Link href="/assumptions/">Review assumptions</Link>.</Notice></div>
 </>;
}
