'use client';
import {Canvas,useFrame} from '@react-three/fiber';
import {OrbitControls,Html,OrthographicCamera} from '@react-three/drei';
import {useEffect,useLayoutEffect,useMemo,useRef,useState,Component} from 'react';
import * as THREE from 'three';
import {useApp} from '@/lib/store';
import type {Asset} from '@/lib/types';
function Blade(){const shape=useMemo(()=>{const s=new THREE.Shape();s.moveTo(-.1,.15);s.lineTo(-.22,1);s.quadraticCurveTo(-.12,2.1,.05,3.05);s.lineTo(.14,3.1);s.lineTo(.2,1.05);s.lineTo(.14,.2);s.closePath();return s;},[]);return <mesh castShadow><extrudeGeometry args={[shape,{depth:.045,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:.025,bevelThickness:.025}]}/><meshStandardMaterial color="#f9faf2" roughness={.55}/></mesh>;}
function Turbine({asset,onSelect,warning}:{asset:Asset;onSelect:(id:string)=>void;warning:boolean}){const rotor=useRef<THREE.Group>(null);const playing=useApp(s=>s.playing);const speed=useApp(s=>s.speed);const [reduced,setReduced]=useState(false);useEffect(()=>{setReduced(window.matchMedia('(prefers-reduced-motion: reduce)').matches);},[]);useFrame((_,delta)=>{if(rotor.current&&playing&&!reduced)rotor.current.rotation.z-=delta*(.55+asset.power_kw/2500)*Math.min(speed,4);});return <group position={[asset.position[0],.04,asset.position[1]]} onClick={e=>{e.stopPropagation();onSelect(asset.id);}}><mesh receiveShadow><cylinderGeometry args={[.85,.85,.18,20]}/><meshStandardMaterial color="#e6e6d8"/></mesh><mesh position={[0,3.65,0]} castShadow><cylinderGeometry args={[.18,.34,7.3,12]}/><meshStandardMaterial color="#f6f6ec" roughness={.6}/></mesh><group position={[0,7.25,0]} rotation={[0,-.3,0]}><mesh position={[0,.1,-.32]} castShadow><boxGeometry args={[.64,.65,1.7]}/><meshStandardMaterial color="#eeefe5"/></mesh><group ref={rotor} position={[0,.07,.62]} rotation={[0,0,asset.position[0]*.5]}><mesh castShadow rotation={[Math.PI/2,0,0]}><coneGeometry args={[.3,.65,16]}/><meshStandardMaterial color="#eff0e7"/></mesh>{[0,1,2].map(i=><group key={i} rotation={[0,0,i*Math.PI*2/3]}><Blade/></group>)}</group></group>{warning&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,.15,0]}><ringGeometry args={[1.25,1.4,40]}/><meshBasicMaterial color="#ce703b" transparent opacity={.8} side={THREE.DoubleSide}/></mesh>}<Html position={[.9,5.8,.9]} center zIndexRange={[8,0]}><button className={`asset-label ${warning?'warning':''}`} onClick={()=>onSelect(asset.id)}>{asset.id}{warning&&<span>!</span>}</button></Html></group>;}
function SolarBlock({asset,onSelect}:{asset:Asset;onSelect:(id:string)=>void}){const ref=useRef<THREE.InstancedMesh>(null);useLayoutEffect(()=>{if(!ref.current)return;const o=new THREE.Object3D();let i=0;for(let z=0;z<4;z++)for(let x=0;x<5;x++){o.position.set(x*.83-1.7,.38+Math.sin(.28)*.5,z*.93-1.4);o.rotation.set(-.28,0,0);o.updateMatrix();ref.current.setMatrixAt(i++,o.matrix);}ref.current.instanceMatrix.needsUpdate=true;},[]);return <group position={[asset.position[0],.1,asset.position[1]]} onClick={e=>{e.stopPropagation();onSelect(asset.id);}}><mesh position={[0,0,0]} receiveShadow><boxGeometry args={[4.45,.08,4.4]}/><meshStandardMaterial color="#b9bd99"/></mesh><instancedMesh ref={ref} args={[undefined,undefined,20]} castShadow><boxGeometry args={[.77,.06,.8]}/><meshStandardMaterial color={asset.status==='Watch'?'#46566a':'#2c485a'} roughness={.38} metalness={.35}/></instancedMesh><Html position={[0,.6,2.6]} center zIndexRange={[7,0]}><button className={`solar-label ${asset.status==='Watch'?'watch':''}`} onClick={()=>onSelect(asset.id)}>{asset.id}</button></Html></group>;}
function Shrubs(){const ref=useRef<THREE.InstancedMesh>(null);useLayoutEffect(()=>{if(!ref.current)return;const o=new THREE.Object3D();for(let i=0;i<90;i++){const x=Math.sin(i*52.7)*15,z=Math.cos(i*39.4)*11;const size=.16+(Math.sin(i*24.3)+1)*.14;o.position.set(x,.1+size*.6,z);o.scale.set(size*1.4,size,size);o.updateMatrix();ref.current.setMatrixAt(i,o.matrix);}ref.current.instanceMatrix.needsUpdate=true;},[]);return <instancedMesh ref={ref} args={[undefined,undefined,90]} castShadow><icosahedronGeometry args={[1,1]}/><meshStandardMaterial color="#718463" roughness={1}/></instancedMesh>;}
function Terrain(){return <group><mesh position={[0,-.52,0]} receiveShadow castShadow><boxGeometry args={[33,1,26]}/><meshStandardMaterial color="#adac8c"/></mesh><mesh position={[0,0,0]} receiveShadow><boxGeometry args={[33,.04,26]}/><meshStandardMaterial color="#c4ccaa"/></mesh>{[-6,2,6].map(z=><mesh key={z} position={[0,.04,z]} receiveShadow><boxGeometry args={[31,.045,.65]}/><meshStandardMaterial color="#ded9ba"/></mesh>)}{[-10,-1,10].map(x=><mesh key={x} position={[x,.06,1]} receiveShadow><boxGeometry args={[.55,.04,23]}/><meshStandardMaterial color="#ded9ba"/></mesh>)}<Shrubs/><group position={[3,.2,4.1]}><mesh position={[0,.45,0]} castShadow><boxGeometry args={[2.2,.9,1.2]}/><meshStandardMaterial color="#e3e3d9"/></mesh><mesh position={[0,.94,0]} castShadow><boxGeometry args={[2.4,.12,1.4]}/><meshStandardMaterial color="#7a8179"/></mesh>{[-.7,0,.7].map(x=><mesh key={x} position={[x,.5,.61]}><boxGeometry args={[.32,.3,.03]}/><meshStandardMaterial color="#3e5557"/></mesh>)}</group><mesh rotation={[-Math.PI/2,0,0]} position={[0,-1.08,0]} receiveShadow><planeGeometry args={[200,200]}/><meshStandardMaterial color="#dce3d2"/></mesh></group>;}
class SceneBoundary extends Component<{children:React.ReactNode;fallback:React.ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}
export default function FarmScene({assets,onSelect,warning=true}:{assets:Asset[];onSelect:(id:string)=>void;warning?:boolean}){return <SceneBoundary fallback={<div className="scene-fallback"><p>3D is unavailable on this device. Select an asset below.</p>{assets.map(a=><button key={a.id} className="button secondary" onClick={()=>onSelect(a.id)}>{a.id}</button>)}</div>}><Canvas shadows dpr={[1,1.5]} gl={{antialias:true,powerPreference:'low-power'}}><color attach="background" args={['#dce3d2']}/><OrthographicCamera makeDefault position={[27,23,33]} zoom={17} near={.1} far={200}/><ambientLight intensity={1.4}/><directionalLight position={[-12,25,10]} intensity={2.8} castShadow shadow-mapSize={[1024,1024]} shadow-camera-left={-30} shadow-camera-right={30} shadow-camera-top={30} shadow-camera-bottom={-30} shadow-normalBias={.04}/><Terrain/>{assets.map(a=>a.type==='wind'?<Turbine key={a.id} asset={a} onSelect={onSelect} warning={a.id==='T-03'&&warning}/>:<SolarBlock key={a.id} asset={a} onSelect={onSelect}/>)}<OrbitControls makeDefault enablePan={false} minZoom={10} maxZoom={28} minPolarAngle={.5} maxPolarAngle={1.15} target={[0,2.2,0]}/></Canvas></SceneBoundary>;}
