'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useEffect,useRef,useState} from 'react';
import {LayoutGrid,Search,Wrench,Sun,ChartNoAxesCombined,Building2,Info,Smartphone,Leaf,Bell,ChevronRight,Menu,X,UserRound,Play,Check,WifiOff,RotateCcw,ArrowUpRight,Command} from 'lucide-react';
import {useApp} from '@/lib/store';
import {API_URL,api,useApiStatus,useBundle} from '@/lib/data';
import {Status} from './ui';
const nav=[{href:'/',name:'Fleet overview',icon:LayoutGrid},{href:'/investigate/',name:'Investigate',icon:Search},{href:'/maintenance/',name:'Maintenance',icon:Wrench},{href:'/solar/',name:'Solar operations',icon:Sun},{href:'/performance/',name:'Performance',icon:ChartNoAxesCombined},{href:'/manager/',name:'Asset manager',icon:Building2},{href:'/about/',name:'About & credits',icon:Info}];
const demo=[{path:'/',title:'Detect a developing warning',copy:'The fleet is a schematic demonstration. Select T-03, then jump to its warning to see a persistent signal become actionable.'},{path:'/investigate/',title:'Investigate the evidence',copy:'Compare measured and expected temperature, inspect the residual and persistence counter, then reveal the injected outcome. These are synthetic signals.'},{path:'/investigate/?compare=true',title:'Separate conditions from deviation',copy:'Compare normal operating variation with the injected degradation window. This illustrates the method; it does not establish real-world accuracy.'},{path:'/maintenance/',title:'Prioritize the right work',copy:'Change available crews from two to one and optimize. Check the changed assignments, unscheduled reasons and estimated cost of waiting.'},{path:'/tech/',title:'Act from the field',copy:'Open the gearbox job, record the checklist and findings, then submit it for review. Demo work is saved in this browser.'},{path:'/solar/',title:'Include the solar fleet',copy:'Inspect inverter performance and the cleaning recommendation. IR examples are clearly marked illustrations.'},{path:'/performance/',title:'Prove only what is measured',copy:'Review the synthetic checks and artifact provenance. Held-out CARE and IR benchmark results stay empty until the real models are evaluated.'}];
export function Shell({children}:{children:React.ReactNode}){
 const path=usePathname();const router=useRouter();const bundle=useBundle();const status=useApiStatus();
 const [mobile,setMobile]=useState(false);const [alerts,setAlerts]=useState(false);const [search,setSearch]=useState('');const [searchOpen,setSearchOpen]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);const state=useApp();const initOrders=state.initOrders;
 useEffect(()=>{if(bundle.data)initOrders(bundle.data.workorders);},[bundle.data,initOrders]);
 useEffect(()=>{if(!state.toast)return;const id=setTimeout(()=>useApp.getState().notify(null),4500);return()=>clearTimeout(id);},[state.toast]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(s=>!s);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 useEffect(()=>{if(searchOpen)dialog.current?.showModal();else dialog.current?.close();},[searchOpen]);
 useEffect(()=>{if(!status.data||!API_URL||state.forceOffline)return;const ws=new WebSocket(API_URL.replace(/^http/,'ws')+'/ws/alerts');ws.onmessage=(event)=>{try{const data=JSON.parse(event.data);if(data.type==='alert')useApp.getState().notify(`${data.asset_id}: ${data.title}`);}catch{}};return()=>ws.close();},[status.data,state.forceOffline]);
 const current=nav.find(n=>n.href==='/'?path==='/':path.startsWith(n.href.slice(0,-1)));
 const count=bundle.data?.alerts.filter(a=>!state.acknowledged.includes(a.id)).length||0;
 const startDemo=()=>{state.setDemo(0);state.setStep(80);state.setPlaying(false);router.push('/');};
 const advance=(index:number)=>{state.setDemo(index);if(index===1){state.selectAsset('T-03');state.setStep(210);}router.push(demo[index].path);};
 const ack=async(id:string)=>{state.ack(id);state.notify('Alert acknowledged. The evidence remains available.');if(status.data)try{await api('/alerts/'+id+'/ack','POST');}catch{state.notify('Acknowledged in this browser. API sync is unavailable.');}};
 return <div className="app-shell">
 <a className="skip-link" href="#main-content">Skip to content</a>
 <aside className={`sidebar ${mobile?'is-open':''}`}>
  <Link href="/" className="brand" aria-label="UrjaKavach home"><div className="brand-mark"><Leaf size={29}/></div><div><strong>UrjaKavach</strong><span>Renewable asset intelligence</span></div></Link>
  <button className="icon-button mobile-close" aria-label="Close navigation" onClick={()=>setMobile(false)}><X size={20}/></button>
  <nav aria-label="Main navigation">{nav.map(n=><Link key={n.href} href={n.href} onClick={()=>setMobile(false)} aria-current={current?.href===n.href?'page':undefined} className={`nav-link ${current?.href===n.href?'active':''}`}><n.icon size={18}/><span>{n.name}</span></Link>)}</nav>
  <div className="sidebar-bottom"><Link href="/tech/" className={`nav-link tech-link ${path.startsWith('/tech')?'active':''}`} onClick={()=>setMobile(false)}><Smartphone size={20}/><div>Technician app<small>Field work, in sync.</small></div><ArrowUpRight size={15}/></Link><div className="workspace-person"><span className="avatar">UK</span><div><strong>Demo workspace</strong><small>Local session · Simulated</small></div></div></div>
 </aside>
 {mobile&&<button className="mobile-backdrop" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={21}/></button><span>Operations</span><ChevronRight size={12}/><strong>{path.startsWith('/tech')?'Technician app':path.startsWith('/assumptions')?'Loss & assumptions':current?.name||'Workspace'}</strong></div><div className="topbar-actions"><button className="search-trigger" onClick={()=>setSearchOpen(true)} aria-label="Search workspace"><Search size={16}/><span>Search</span><kbd>⌘ K</kbd></button><button className="icon-button alert-button" onClick={()=>setAlerts(true)} aria-label={`Open alert center, ${count} unacknowledged`}><Bell size={18}/>{count>0&&<b>{count}</b>}</button><label className="role-select"><UserRound size={15}/><select aria-label="Demo role" value={state.role} onChange={e=>{const role=e.target.value as typeof state.role;state.setRole(role);router.push(role==='technician'?'/tech/':role==='manager'?'/manager/':'/');}}><option value="operator">Operator</option><option value="technician">Technician</option><option value="manager">Asset manager</option></select></label><button className="button primary demo-trigger" onClick={startDemo}><Play size={14}/>Start guided demo</button></div></header>
 {(state.forceOffline||(API_URL&&!status.isPending&&!status.data))&&<div className="offline-banner"><WifiOff size={15}/><strong>Offline demo data</strong><span>Using the bundled simulated scenario. Changes stay in this browser.</span></div>}
 <main id="main-content" className={`page-content ${path.startsWith('/tech')?'tech-content':''}`}>{children}</main>
 <footer className="app-footer"><span><span className="tiny-dot"/>{status.data?'Python API connected':'Bundled demo'} · All operational data is simulated</span><div><button onClick={()=>state.setOffline(!state.forceOffline)}>{state.forceOffline?'Exit offline demo':'Try offline mode'}</button><span>·</span><button onClick={()=>{state.reset();router.push('/');}}><RotateCcw size={12}/>Reset demo</button><Link href="/about/">Data & credits</Link></div></footer>
 </div>
 {alerts&&<div className="drawer-backdrop" onClick={()=>setAlerts(false)}><section className="alert-drawer" role="dialog" aria-modal="true" aria-label="Alert center" onClick={e=>e.stopPropagation()}><header><div><h2>Alert center</h2><p>Review, acknowledge and act.</p></div><button className="icon-button" aria-label="Close alert center" onClick={()=>setAlerts(false)}><X size={20}/></button></header>{bundle.data?.alerts.map(a=><article className="drawer-alert" key={a.id}><div className="row-between"><strong>{a.asset_id}</strong><Status value={state.acknowledged.includes(a.id)?'Acknowledged':a.severity}/></div><h3>{a.title}</h3><p>{a.detail}</p><small>Simulated signal · {a.subsystem}</small><div className="button-row"><button className="button secondary small" onClick={()=>{state.selectAsset(a.asset_id);router.push(a.asset_id.startsWith('S')?'/solar/':'/investigate/');setAlerts(false);}}>Investigate</button><button className="button ghost small" disabled={state.acknowledged.includes(a.id)} onClick={()=>ack(a.id)}><Check size={14}/>{state.acknowledged.includes(a.id)?'Acknowledged':'Acknowledge'}</button></div></article>)}<div className="notice">Cloud delivery and escalation use the optional Python alert service. No Slack delivery is claimed in this demo.</div></section></div>}
 <dialog ref={dialog} className="command-dialog" onClose={()=>setSearchOpen(false)}><div className="command-input"><Search size={19}/><input aria-label="Search assets and pages" placeholder="Find an asset or open a page…" value={search} onChange={e=>setSearch(e.target.value)} autoFocus/><button className="icon-button" aria-label="Close search" onClick={()=>setSearchOpen(false)}><X size={18}/></button></div><div className="command-results">{nav.filter(n=>n.name.toLowerCase().includes(search.toLowerCase())).map(n=><Link key={n.href} href={n.href} onClick={()=>setSearchOpen(false)}><n.icon size={17}/>{n.name}<ChevronRight size={14}/></Link>)}{bundle.data?.assets.filter(a=>(a.id+' '+a.name).toLowerCase().includes(search.toLowerCase())).slice(0,5).map(a=><button key={a.id} onClick={()=>{state.selectAsset(a.id);setSearchOpen(false);router.push(a.type==='wind'?'/investigate/':'/solar/');}}><Search size={16}/>{a.id} — {a.name}<Status value={a.status}/></button>)}</div><small><Command size={12}/> Keyboard shortcut · Escape to close</small></dialog>
 {state.demoStep!==null&&<aside className="guided-demo" aria-label="Guided demo"><div className="row-between"><span>Guided demo · {state.demoStep+1} of {demo.length}</span><button className="icon-button" aria-label="Close guided demo" onClick={()=>state.setDemo(null)}><X size={17}/></button></div><div className="demo-progress">{demo.map((_,i)=><button key={i} className={i<=state.demoStep!?'filled':''} aria-label={`Demo step ${i+1}`} onClick={()=>advance(i)}/>)}</div><h3>{demo[state.demoStep].title}</h3><p>{demo[state.demoStep].copy}</p><div className="row-between"><button className="button ghost small" disabled={state.demoStep===0} onClick={()=>advance(state.demoStep!-1)}>Previous</button><button className="button primary small" onClick={()=>state.demoStep===demo.length-1?state.setDemo(null):advance(state.demoStep!+1)}>{state.demoStep===demo.length-1?'Finish demo':'Next step'}</button></div></aside>}
 {state.toast&&<div className="toast" role="status"><Check size={17}/>{state.toast}<button aria-label="Dismiss notification" onClick={()=>state.notify(null)}><X size={14}/></button></div>}
 </div>;
}
