/* eslint-disable @next/next/no-img-element -- Tiny pixel illustrations and temporary user-upload blob previews are intentionally unoptimized. */
'use client';
import Link from 'next/link';
import {useState} from 'react';
import {Sun,Camera,Droplets,Download,ClipboardPlus} from 'lucide-react';
import {useSolar,useBundle,inr,downloadJson} from '@/lib/data';
import {useApp} from '@/lib/store';
import {PageHeading,Panel,Stat,Notice,Loading,ErrorState,Provenance} from '@/components/ui';
import {Chart,lineOption} from '@/components/charts';
export default function SolarPage(){const q=useSolar(),bundle=useBundle();const state=useApp();const [block,setBlock]=useState('All blocks');const [chosen,setChosen]=useState<string|null>(null);if(q.isPending)return <Loading/>;if(!q.data)return <ErrorState message="Solar artifacts could not be loaded." retry={()=>q.refetch()}/>;const data=q.data,rows=data.inverters.filter(i=>block==='All blocks'||i.block===block),selected=data.inverters.find(i=>i.id===chosen)||rows[0];
 const createCleaning=()=>{if(state.orders.some(o=>o.asset_id==='S-02'&&o.status!=='Completed')){state.notify('S-02 already has an open work order.');return;}state.addOrder({id:`WO-S02-${Date.now()}`,asset_id:'S-02',title:'Inspect and clean underperforming modules',status:'Assigned',priority:'Medium',crew:'Crew 2',skill:'solar',duration_hours:3,checklist:[{text:'Confirm isolation and approved cleaning procedure',done:false},{text:'Inspect modules for visible soiling and damage',done:false},{text:'Record before and after output under comparable conditions',done:false}],notes:'Simulated cleaning recommendation. Confirm actual field conditions.',provenance:'Simulated'});state.notify('Cleaning work order created.');};
 return <><PageHeading title="Every panel has potential." description="Find persistent underperformance. Plan an inspection that pays back." actions={<><button className="button secondary" onClick={()=>downloadJson('urjakavach-solar.json',data)}><Download size={14}/>Export data</button><Link className="button primary" href="/tech/?view=inspection"><Camera size={15}/>Inspect a module</Link></>}/><div className="stats-strip"><Stat label="Inverters in view" value={String(rows.length)} icon={<Sun size={20}/>}/><Stat label="Average performance index" value={`${(rows.reduce((s,i)=>s+i.performance_index,0)/rows.length*100).toFixed(1)}%`} detail="Actual ÷ expected output"/><Stat label="Cleaning opportunity" value={inr(data.cleaning.daily_loss_inr)} detail="Estimated daily exposure · S-02"/><Stat label="Observation window" value={`${data.days.length} days`} detail="Simulated solar operating days"/></div>
 <div className="solar-grid section-gap"><Panel title="Inverter performance" subtitle="Persistent low output stands out across days." action={<select aria-label="Solar block" value={block} onChange={e=>setBlock(e.target.value)}>{['All blocks','S-01','S-02','S-03','S-04'].map(b=><option key={b}>{b}</option>)}</select>}><div className="solar-heatmap"><div className="heatmap-heading"><span>Inverter</span><div>{data.days.map((d,i)=><span key={d}>{i%4===0?`D${d}`:''}</span>)}</div><span>Today</span></div>{rows.map(inv=><button key={inv.id} className={`heatmap-row ${selected?.id===inv.id?'selected':''}`} onClick={()=>setChosen(inv.id)}><span>{inv.id}<small>{inv.block}</small></span><div>{inv.values.map((v,i)=><i key={i} style={{background:v<.78?'#ce703b':v<.9?'#e4ad72':v<.97?'#b7cf9e':'#3d7154'}} title={`Day ${data.days[i]}: ${(v*100).toFixed(1)}%`}/>)}</div><strong>{(inv.performance_index*100).toFixed(0)}%</strong></button>)}</div><div className="heatmap-legend"><span>Performance index</span><i style={{background:'#ce703b'}}/>Below 78%<i style={{background:'#e4ad72'}}/>78–90%<i style={{background:'#b7cf9e'}}/>90–97%<i style={{background:'#3d7154'}}/>97%+</div><div className="panel-body"><Notice>All values are simulated. Low performance is a reason to inspect; shading, clipping, sensor error and equipment condition can produce similar patterns.</Notice></div></Panel>
 <Panel title="A small clean. A clearer return." subtitle="S-02 · illustrative cleaning decision" className="cleaning-panel"><div className="cleaning-visual"><Sun size={40} strokeWidth={1}/><div className="mini-panels">{Array.from({length:12},(_,i)=><span key={i}/>)}</div><Droplets size={26}/></div><div className="panel-body"><div className="row-between"><span>Recommended planning day</span><strong>Day {data.cleaning.recommended_day}</strong></div><dl className="data-dl"><div><dt>Estimated energy loss / day</dt><dd>{data.cleaning.daily_loss_kwh} kWh</dd></div><div><dt>Illustrative cleaning cost</dt><dd>{inr(data.cleaning.cost_inr)}</dd></div><div><dt>Assumed tariff</dt><dd>₹{data.cleaning.tariff}/kWh</dd></div></dl><p className="small muted">{data.cleaning.formula}. Weather and access must be checked before dispatch.</p><button className="button primary full-width" onClick={createCleaning}><ClipboardPlus size={14}/>Create cleaning work order</button><Link className="text-link section-gap" href="/maintenance/">Review crew availability</Link></div></Panel></div>
 <div className="two-columns section-gap"><Panel title={selected?`${selected.id} · daily performance`:'Daily performance'} subtitle="An inverter-level view of gradual decline."><Chart height={260} label="Selected inverter performance index by day" option={lineOption(data.days,[{name:'Performance index',data:selected?.values||[],color:'#1e5440',area:true}], 'Ratio',.9)}/><div className="panel-body"><span className="chip">Conversion efficiency: {selected?`${(selected.efficiency*100).toFixed(1)}%`:'—'}</span></div></Panel><Panel title="Actual versus expected" subtitle="Fleet example · irradiation and module-temperature response"><Chart height={260} label="Simulated solar output actual versus expected" option={lineOption(data.trend.map(p=>p.day),[{name:'Expected',data:data.trend.map(p=>p.expected),color:'#93ab89',dashed:true},{name:'Actual',data:data.trend.map(p=>p.actual),color:'#ce703b'}],'kW')}/><div className="panel-body"><Provenance/></div></Panel></div>
 <Panel title="Infrared field guide" subtitle="Illustrative single-module patterns, with human-authored inspection suggestions." action={<Link className="button secondary small" href="/tech/?view=inspection">Open inspection</Link>} className="section-gap"><div className="ir-gallery">{bundle.data?.ir_samples.map(sample=><div key={sample.id} className="ir-card"><img src={sample.image} alt={`Synthetic infrared illustration: ${sample.label}`} width={160} height={96}/><h3>{sample.label}</h3><p>{sample.action}</p><span className="chip">Illustration · not a prediction</span></div>)}</div></Panel></>;
}
